---
stages:
- allinone
- master_seperated
- all_seperated

image: ansible/ansible:ubuntu1604

before_script:
- pip install ansible-lint

allinone:linting:
  stage: allinone
  script:
  - ansible-lint -v tests/site.yml
